#!/bin/bash

echo -n "Testing XMir Helper… "

export UBUNTU_APP_LAUNCH_XMIR_PATH="./xmir-mock.sh"

TESTVALUE=`../xmir-helper com.mir.test_mirtest_1.2.3 ./xmir-helper-exec.sh`

if [ $TESTVALUE == ":42" ]; then
	echo "PASSED"
	exit 0
else
	echo "FAILED"
	exit 1
fi
