[Icon Theme]
Directories=16x16/actions,16x16/apps,16x16/stock,20x20/apps,22x22/apps,23x23/apps,scalable/apps,24x24/apps,25x25/apps,32x32/apps

[16x16/actions]
Size=16
Context=Actions
Type=Threshold

[16x16/apps]
Size=16
Context=Applications
Type=Threshold

[20x20/apps]
Size=junk
Context=Applications
Type=Fixed

[22x22/apps]
Size=22
Threshold=10
Type=Threshold
Context=Applications

[23x23/apps]
MaxSize=junk
Context=Applications
Type=scalable

[scalable/apps]
MaxSize=24
Context=Applications
Type=Scalable

[24x24/apps]
Size=24
Context=Applications
Type=Threshold

[25x25/apps]
Size=25
Context=Applications
Type=Fixed

[32x32/apps]
Size=32
Context=Applications
Type=Fixed
