[Icon Theme]
Directories=16x16/actions,16x16/apps,scalable/apps,24x24/apps,25x25/apps,32x32/apps

[16x16/actions]
Size=16
Context=Actions
Type=Threshold

[16x16/apps]
Size=16
Context=Applications
Type=Threshold

[scalable/apps]
MaxSize=24
Context=Applications
Type=Scalable

[24x24/apps]
Size=24
Context=Applications
Type=Threshold

[25x25/apps]
Size=25
Context=Applications
Type=Fixed

[32x32/apps]
Size=32
Context=Applications
Type=Threshold
